# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JenkinsTopSubmitters < Formula
  desc "Jenkins Submitter Pivot Table analyzer."
  homepage "https://github.com/jmMeessen/jenkins-top-submitters"
  version "1.2.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jmMeessen/jenkins-top-submitters/releases/download/v1.2.6/jenkins-top-submitters_1.2.6_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "94a9d7d2b0a00483af9cc5a843dfb7d8681d604572b4abfcaea9aa780e8a51d8"

      def install
        bin.install "jenkins-top-submitters"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jmMeessen/jenkins-top-submitters/releases/download/v1.2.6/jenkins-top-submitters_1.2.6_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "b4617d7039e6f5c4d1e5be50cc6ecd2c7e2798072796208cda3ee18229ed03eb"

      def install
        bin.install "jenkins-top-submitters"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmMeessen/jenkins-top-submitters/releases/download/v1.2.6/jenkins-top-submitters_1.2.6_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "9fc6edb360dcbe4b0ab85064d9d3850859174e514a1df2ed920a688fe038b0b6"

      def install
        bin.install "jenkins-top-submitters"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jmMeessen/jenkins-top-submitters/releases/download/v1.2.6/jenkins-top-submitters_1.2.6_linux_armv6.tar.gz", using: CurlDownloadStrategy
      sha256 "b051db39cb953837cf4d8980e099ee812568a93b9b4e5ccec92fd26067516840"

      def install
        bin.install "jenkins-top-submitters"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jmMeessen/jenkins-top-submitters/releases/download/v1.2.6/jenkins-top-submitters_1.2.6_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "12fd9cb59862c1d85edbc27ca502821076100d4a1ef89a09d588772a9802a51c"

      def install
        bin.install "jenkins-top-submitters"
      end
    end
  end

  test do
    system "#{bin}/jenkins-top-submitters version -d"
  end
end
