# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JenkinsGetCommenters < Formula
  desc "Jenkins Submitter Pivot Table analyzer."
  homepage "https://github.com/jmMeessen/jenkins-get-commenters"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jmMeessen/jenkins-get-commenters/releases/download/v0.1.1/jenkins-get-commenters_0.1.1_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "ba17fe08aa55b00059d46e17a28fffc8f21dfd30ec5a6d68f6943d05b23de6a9"

      def install
        bin.install "jenkins-get-commenters"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jmMeessen/jenkins-get-commenters/releases/download/v0.1.1/jenkins-get-commenters_0.1.1_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "d4912b8aba126771f2d626afd84491fe58a738d128ac756aa18ab2def9599fd6"

      def install
        bin.install "jenkins-get-commenters"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jmMeessen/jenkins-get-commenters/releases/download/v0.1.1/jenkins-get-commenters_0.1.1_linux_armv6.tar.gz", using: CurlDownloadStrategy
      sha256 "621028886f8650795ca529148066546639bfecf84e33853be41f8eb6bf8b486c"

      def install
        bin.install "jenkins-get-commenters"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmMeessen/jenkins-get-commenters/releases/download/v0.1.1/jenkins-get-commenters_0.1.1_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "4c8f3329e78e403f9dbdd620e0bea5fdd0e93e9f56230990305f741ebca3293b"

      def install
        bin.install "jenkins-get-commenters"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jmMeessen/jenkins-get-commenters/releases/download/v0.1.1/jenkins-get-commenters_0.1.1_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "f76a68b87bd440d2edf5ef59b1d2c4b8d87b2585c2af2bf40ff0b2e14aff0b4d"

      def install
        bin.install "jenkins-get-commenters"
      end
    end
  end

  test do
    system "#{bin}/jenkins-get-commenters version -d"
  end
end
