# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JenkinsGetCommenters < Formula
  desc "Jenkins Submitter Pivot Table analyzer."
  homepage "https://github.com/jmMeessen/jenkins-get-commenters"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jmMeessen/jenkins-get-commenters/releases/download/v0.1.0/jenkins-get-commenters_0.1.0_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "1c7ecc64a1dacfc89e36c29318a81e2546aa02ed97e5af4a9b55e48244cbd2cf"

      def install
        bin.install "jenkins-get-commenters"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jmMeessen/jenkins-get-commenters/releases/download/v0.1.0/jenkins-get-commenters_0.1.0_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "5a4a390bb4f8ee0093772a8a0b9b96873131a2f7bad50e89f28d61f87a868647"

      def install
        bin.install "jenkins-get-commenters"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jmMeessen/jenkins-get-commenters/releases/download/v0.1.0/jenkins-get-commenters_0.1.0_linux_armv6.tar.gz", using: CurlDownloadStrategy
      sha256 "2e0cc8751aa39e810cd0f1169cf7de7e69c1ce5eec4db6120cef6ffb9ad2189b"

      def install
        bin.install "jenkins-get-commenters"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmMeessen/jenkins-get-commenters/releases/download/v0.1.0/jenkins-get-commenters_0.1.0_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "23caae205b30967753d721841ec45888b1b1e39254ed0a979e7fba6c9ca4191c"

      def install
        bin.install "jenkins-get-commenters"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jmMeessen/jenkins-get-commenters/releases/download/v0.1.0/jenkins-get-commenters_0.1.0_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "6baabb1007c47292e87fb8f752aafd681ac83e5930c76a0b9cbc6bd37f046f5a"

      def install
        bin.install "jenkins-get-commenters"
      end
    end
  end

  test do
    system "#{bin}/jenkins-get-commenters version -d"
  end
end
