# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JenkinsStats < Formula
  desc "Jenkins Submitter Pivot Table analyzer."
  homepage "https://github.com/jmMeessen/jenkins-stats"
  version "0.2.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jmMeessen/jenkins-stats/releases/download/v0.2.5/jenkins-stats_0.2.5_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "ab08340b2db7f55ddfb9ab067ce8304655f9f5e13c505ce149f5f6025d978ada"

      def install
        bin.install "jenkins-stats"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jmMeessen/jenkins-stats/releases/download/v0.2.5/jenkins-stats_0.2.5_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "0e8b05240b6cc970a400ffdf5e2e0c35cf71a280f6fc0c75bd1f6e4774344b08"

      def install
        bin.install "jenkins-stats"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jmMeessen/jenkins-stats/releases/download/v0.2.5/jenkins-stats_0.2.5_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "32b97f21cc0621dccdedfc8ebf990c3b6d92f84d011368be7e6c79bf67353d9c"

      def install
        bin.install "jenkins-stats"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmMeessen/jenkins-stats/releases/download/v0.2.5/jenkins-stats_0.2.5_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "608b3d18aae7375690ecbfe227f66fd1b8151c46d634bee8092ff38e591e5284"

      def install
        bin.install "jenkins-stats"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jmMeessen/jenkins-stats/releases/download/v0.2.5/jenkins-stats_0.2.5_linux_armv6.tar.gz", using: CurlDownloadStrategy
      sha256 "19f12ea4c27e3585f2c382bbdca67897210f425e45f9262bfb64aeb7aef0bdfd"

      def install
        bin.install "jenkins-stats"
      end
    end
  end

  test do
    system "#{bin}/jenkins-stats version -d"
  end
end
