# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JenkinsStats < Formula
  desc "Jenkins Submitter Pivot Table analyzer."
  homepage "https://github.com/jmMeessen/jenkins-stats"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jmMeessen/jenkins-stats/releases/download/v0.2.1/jenkins-stats_0.2.1_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "b21bd5a1a6444c081fedb0ce71fc3d7ba6b325ca7ddc8e18b897795a02363f41"

      def install
        bin.install "jenkins-stats"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jmMeessen/jenkins-stats/releases/download/v0.2.1/jenkins-stats_0.2.1_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "f6685f6dc2b2d45242f3ba480c464b1f672996f2dc209b22510a1e26236c9c29"

      def install
        bin.install "jenkins-stats"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jmMeessen/jenkins-stats/releases/download/v0.2.1/jenkins-stats_0.2.1_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "bc5821201c8d2f1dfa00ed0ab703ec111014cc2bc8d5ff3b16282261d6eb68e4"

      def install
        bin.install "jenkins-stats"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jmMeessen/jenkins-stats/releases/download/v0.2.1/jenkins-stats_0.2.1_linux_armv6.tar.gz", using: CurlDownloadStrategy
      sha256 "8995a9c52e5e0267ba9503530cd7a4104f64a69c9ed2a8f6bb9eded6288a6df0"

      def install
        bin.install "jenkins-stats"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmMeessen/jenkins-stats/releases/download/v0.2.1/jenkins-stats_0.2.1_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "fcb89472e810736be148a1615869efde45031faeeac782753f02f5ec040b120b"

      def install
        bin.install "jenkins-stats"
      end
    end
  end

  test do
    system "#{bin}/jenkins-stats version -d"
  end
end
